name: rinde
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Iconos estilo iOS
  cupertino_icons: ^1.0.8
  gal: ^2.3.0
  flutter_local_notifications: ^17.0.0

  # --- TUS DEPENDENCIAS ORIGINALES ---
  flutter_svg: ^1.1.6
  sqflite: ^2.3.0
  path: ^1.8.3
  sqflite_common_ffi: ^2.3.0
  sqflite_common_ffi_web: ^0.4.0

  # --- DEPENDENCIAS NECESARIAS PARA HOME Y WALLET ---
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # He bajado esta versión a la 2.0.0 porque la 6.0.0 causa conflicto con tu SDK actual
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Configuración de imágenes
  assets:
    - assets/images/